# Generated by Django 2.0.5 on 2018-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('altitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
