# Generated by Django 2.2.14 on 2021-01-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.PositiveSmallIntegerField(blank=True, default=False, null=True)),
                ('time', models.DateTimeField()),
                ('wind_direction', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Windrichting (in graden) gemiddeld over de laatste 10 minuten van het afgelopen uur (360=noord, 90=oost, 180=zuid, 270=west, 0=windstil 990=veranderlijk', max_digits=8, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Uurgemiddelde windsnelheid (in m/s)', max_digits=8, null=True)),
                ('gust_of_wind', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Hoogste windstoot (in m/s) over het afgelopen uurvak', max_digits=8, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Temperatuur (in graden Celsius) op 1.50 m hoogte tijdens de waarneming', max_digits=8, null=True)),
                ('dew_temperature', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Dauwpuntstemperatuur (in graden Celsius) op 1.50 m hoogte tijdens de waarneming', max_digits=8, null=True)),
                ('sunshine', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Duur van de zonneschijn (in uren) per uurvak, berekend uit globale straling  (-1 for <0.05 uur)', max_digits=8, null=True)),
                ('radiation', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Globale straling (in J/cm2) per uurvak', max_digits=8, null=True)),
                ('precipitation_duration', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Duur van de neerslag (in uren) per uurvak', max_digits=8, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Uursom van de neerslag (in mm) (-1 voor <0.05 mm)', max_digits=8, null=True)),
                ('air_pressure', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Luchtdruk (in hPa) herleid naar zeeniveau, tijdens de waarneming', max_digits=8, null=True)),
                ('visibility', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Horizontaal zicht tijdens de waarneming (0=minder dan 100m, 1=100-200m, 2=200-300m,..., 49=4900-5000m, 50=5-6km, 56=6-7km, 57=7-8km, ..., 79=29-30km, 80=30-35km, 81=35-40km,..., 89=meer dan 70km)', max_digits=8, null=True)),
                ('cloud_cover', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Bewolking (bedekkingsgraad van de bovenlucht in achtsten), tijdens de waarneming (9=bovenlucht onzichtbaar)', max_digits=8, null=True)),
                ('relative_humidity', models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Relatieve vochtigheid (in procenten) op 1.50 m hoogte tijdens de waarneming', max_digits=8, null=True)),
                ('mist', models.BooleanField(default=False, help_text='Mist wel/niet voorgekomen in het voorgaande uur en/of tijdens de waarneming')),
                ('rain', models.BooleanField(default=False, help_text='Regen wel/niet voorgekomen in het voorgaande uur en/of tijdens de waarneming')),
                ('snow', models.BooleanField(default=False, help_text='Sneeuw wel/niet voorgekomen in het voorgaande uur en/of tijdens de waarneming')),
                ('lightning', models.BooleanField(default=False, help_text='Onweer wel/niet voorgekomen in het voorgaande uur en/of tijdens de waarneming')),
                ('icing', models.BooleanField(default=False, help_text='IJsvorming wel/niet voorgekomen in het voorgaande uur en/of tijdens de waarneming')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='stations.Station')),
            ],
        ),
    ]
